
const Map<String, String> en_roles ={
  "User":"User",
  "Doctor":"Doctor",
  "Admin":"Admin",
};
const Map<String, String> en_pages ={
  'Home':'Home',
  'Speech Recognition':'Speech Recognition',
  'Text Copied to Clipboard':'Text copied to clipboard',
  'Click button to start recording':'Click button to start recording',
};
const Map<String, String> _en = {
  "AppName":"Mom's Care",
  "AppDescribe":"Mom's Care",
  "Arabic":"Arabic",
  "English":"English",
  "Home": "Home",
  "Schedule": "Schedules",
  "Departments": "Departments",
  "Aboute": "Aboute",
  "Class":"Class",
  "Save": "Save",
  "Publish": "Publish",
  "Department": "Department",
  "Section": "Section",
  "StartDate": "StartDate",
  "EndtDate": "EndtDate",

  "Wait..": "Wait..",
  "School year": "School year",
  'View hall information': "View hall information",
  'Lectures': "daily lectures",
  'Contact Us':'Contact Us',
  "LogOut": "LogOut",
  "Enter First Name": "Enter First Name",
  "Enter Last Name": "Enter Last Name",
  'Change language':  'Changed language',
  "Profile": "Profile",
  "LevelId": "Academic level number",
  "Level": "School level",
  "Enter the full name": "Enter the full name",
  "Choose your academic level": "Choose your academic level",
  "Choose the academic department": "Choose the academic department",
  "Choose your college": "Choose your college",
  "Enter the academic number":"Enter the academic number",
  "SudentId": "Academic student number",
  "Academic Id": "Academic number",
  "SectionId": "Section number",

  "Edit personal email": "Edit personal email",
  "Edit personal name":"Edit personal name",
  "Do you really want to log out":"Do you really want to log out",
  "Diagnoses": "Diagnoses",
  "Settings":  "Settings",
  "Update":"Update",
  "Edit": "Edit",
  "Delete": "Delete",
  "Current Password": "Current Password",
  "Enter Password": "Enter Password",
  "New Password": "New Password",
  "Colleges": "Colleges",
  "Enter New Password": "Enter the new password",
  "Enter Current Password": "Enter Current Password",
  "Change Password":"Changed Password",
  "Total diagnoses":"Total diagnoses",
  "Diagnosis analyses":  "Diagnosis analyses",
  "Diagnosis":  "Diagnosis",
  "NeedsHealthCare": "Needs Health Care",
  "Login": "Login",
  "Register": "Register",
  "Create an account":   "Create an account",
  "Email": "Email ",
  "First Name": "First Name",
  "Last Name": "Last Name",
  "Password": " Password",
  "Confirm Password":  "Confirm Password",
  "ُError": "ُError !",
  "Ok": "OK",
  "Cancel": "Cancel",
  "Verification code": "verification code",
  "Confirm verification code": "Confirm verification code",
  "Enter valid email": " Enter valid email",
  "Enter secure password": " Enter secure password",
  "Enter Confirm Password": " Enter Confirm Password",
  "Forgot Password": "Forgot Password ?",
  "Reset Password":  "Reset Password",
  'Enter your email':  'Enter your email',
  'Send':  'Send',
  'Alert':  'Alert',
  "New User": "New User ?",
  "Create Account": "Create Account",
  "You Have An Account ?":   "You have an account ?",
  "end": "end",
  "List of healthy foods":"List of healthy foods",
  "List of harmful foods":"List of harmful foods",
  "loading":" loading... ",
  "please wait":"Please Wait",
  'Take a picture for medical analysis':'Take a picture for medical analysis',
  'Upload medical analysis image':'Upload medical analysis image',
  'No Text Found':  'No Text Found',
  "No text was found in the image, use another medical analysis image":  "No text was found in the image, use another medical analysis image",
  "Tips and instructions medical": "Tips and instructions medical",
  "Your medical analysis is now diagnosed":"Your medical analysis is now diagnosed",
  "A list of healthy foods is now being brought":"A list of healthy foods is now being brought",
  "A list of unhealthy foods is now being brought":"A list of healthy foods is now being brought",
  "A list of medical advice and instructions is now being brought":"A list of medical advice and instructions is now being brought",
  "wait The medical report is diagnosing":"The medical report is diagnosing. Wait until the process is completed",
  "Wait until the diagnostic process is finished":"Wait until the diagnostic process is finished ",
  "Choose how to upload the analysis image":"You can upload an image of the medical analysis either through the camera or by choosing an image from the storage memory",
};
const Map<String, String> en_languages = {
  "Arabic":"Arabic",
  "English":"English",

};
const Map<String, String> en_days = {
  "monday": "Monday",
  "tuesday": "Tuesday",
  "wednesday": "Wednesday",
  "thursday": "Thursday",
  "friday": "Friday",
  "saturday": "Saturday",
  "sunday": "Sunday"
};
const Map<String, String> en_labels = {
  "Camera":"Camera",
  "Diagnostic result":"Diagnostic result",
  "Previous analyses": "Previous analyses",
  "Gallery":"Gallery",
  "Choose the image source":"Choose the image source",
  "Healthy foods":"Healthy foods",
  "Harmful foods":"Harmful foods",
  "Tips and instructions":"Tips and instructions",
  "Analysis results":"Analysis results",
  "Evaluation and diagnosis":"Evaluation and diagnosis",
  "SeeYourDoctor":"See Your Doctor",
  "Natural":"Natural",
  "no content":"no content",
  "NeedsHealthCare":"Needs Health Care",
  "List of previous diagnoses":"List of previous diagnoses",
  "The current diagnosis request will be cancelled. Are you ok with that":"The current diagnosis request will be cancelled. Are you ok with that ?",
  "Do you want to cancel the current order already":  "Do you want to cancel the current order already ?",
  "The diagnostics you previously performed are now loaded":"The diagnostics you previously performed are now loaded",
  "Do you really want to delete the current diagnostic process":"Do you really want to delete the current diagnostic process",
  "The process was completed successfully":"The process was completed successfully",
};
const Map<String, String> en_errors = {

"You have no lectures today":"You have no lectures today",
  "The password must contain at least 8 characters, uppercase and lowercase letters, and symbols":"The password must contain at least 8 characters, uppercase and lowercase letters, and symbols",
  "no connection":"no connection",
  "No Internet connection": "There is no network. Check the Internet connection!!",
  "Empty": "Empty, no content",
  "Field is Empty":"You cannot leave the input field blank",
  "Email is invalid":"Email is invalid",
  "name is invalid":"name is invalid",
  "student id is invalid":"student id is invalid",
  "Login failed":"Login failed",
  "Login successful":"Login successful",
  "Register successful":"Register successful",
  "Register failed":"Register failed",
  "Password does not match":"Password does not match",
  "Password is inValid":"Password is inValid",
  "Password is not Valid": "The password must contain uppercase and lowercase letters, numbers and symbols, and must not be less than 6 characters.",
  "unexpected error":"An unexpected error occurred, please try again",
  "Failed operation": "The operation failed, please try again.",
  "Different password": "The new password is identical to the current password. You must use a different password.",
  "Different email": "You must use a different email from the previous email.",
  "No Text Found":"No text was found in the image, use another image",
  "The image content is invalid":"NThe image content is invalid",
  "Diagnosis was invalid":"The diagnostic process was invalid. Please repeat the diagnosis again.",
};
const Map<String, String> en_aboute= {

"Aboute App": "It is an application that allows students of the University College in Al-Khurma to view the academic schedules, daily lecture information, and the location of the classrooms and lectures.",
"Features":"Features",
"Diagnosis and medical tests": "View the study schedule",
"Suggesting advice and instructions according to the patient’s health condition": "View daily lectures for a student",
"Proposing a list of harmful and beneficial foods according to the patient’s health condition": "View academic departments",
"Options to copy diagnosis result as text and share": "Browse the academic schedules for the departments",
'We value your input and are here to help. If you have any questions, feedback, or need assistance, please contact us':"We value your input and are here to help. If you have any questions, comments or need assistance, please contact us.",
};
const Map<String, String> en_schedule = {
  "School schedule":"School schedule",
  "School year":"School year",
  "Section":"Section",
  "Schools schedules": "Schools schedules",
  "Daily Schedule":"Daily Schedule",
  "Other":"Other",
  "Starting date":"Starting date",
  "Expiry date":"Expiry date",
  "Day":"Day",
  "Material":"Material",
  "Teacher":"The teacher",
  "Time":"Time",
};
Map<String, String> get en {
  return {}
    ..addAll(_en)
    ..addAll(en_errors)
    ..addAll(en_aboute)
    ..addAll(en_labels)
    ..addAll(en_days)
    ..addAll(en_schedule)
    ..addAll(en_pages)
    ..addAll(en_roles)
    ..addAll(en_languages);
}