// ignore_for_file: constant_identifier_names
//!============CAHCHED SHARED PREFERENCES ====
const INFO_ACCOUNT_CACHED = "INFO_ACCOUNT_CACHED";
const PROFILE_INFO_CACHED = "PROFILE_INFO_CACHED";
const POSTS_DATA_CACHED = "POST_DATA_CACHED";
const REFRESH_PROFILE_CACHED = "REFRESH_PROFILE_CACHED";


const AUTH_TOKEN_CACHED = "AUTH_TOKEN";
const AUTH_USERID_CACHED = "AUTH_USERID";
const AUTH_ROLE_CACHED = "AUTH_ROLE";

const LANGUAGE_TYPE_CACHED = "LANGUAGE_TYPE";
const SPEECH_LANGUAGE_TYPE_CACHED = "SPEECH_LANGUAGE_TYPE";

const AUTH_CACHED = "AUTH_CACHED";

const USER_ID = "USER_ID";

const String IS_AUTH = "IS_AUTH";

const CACHED_FLEETKEY = "CACHED_FLEETKEY";

const ORDER_CACHED = "ORDER_CACHED";

//!============CAHCHED HIVE =================

const MY_LOCATION_KEY = 'myLocationKey';
